# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   creationTimestamp: null
#   labels:
#     app: nextjs
#   name: nextjs
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: nextjs
#   strategy: {}
#   template:
#     metadata:
#       creationTimestamp: null
#       labels:
#         app: nextjs
#     spec:
#       containers:
#         # - image: public.ecr.aws/b5c5s7l4/adityaprakash2811/nodek8:latest
#         - image: public.ecr.aws/f4u9x2g7/nextjs:latest
#           name: nextjs
#           imagePullPolicy: Always
#           resources: {}
#           ports:
#             - containerPort: 3000
# status: {}

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nextjs
#   labels:
#     run: nextjs
# spec:
#   ports:
#     - port: 3000
#       protocol: TCP
#   selector:
#     app: nextjs
#   type: NodePort
apiVersion: v1
kind: Service
metadata:
  name: nextjs
spec:
  selector:
    app: nextjs
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: public.ecr.aws/f4u9x2g7/nextjs:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
